export const SHOW_SIDEBAR = 'SHOW_SIDEBAR';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const USERS_START = 'USERS_START';
export const USERS_CONCAT = 'USERS_CONCAT';
export const USERS_SUCCESS = 'USERS_SUCCESS';
export const USERS_FAIL = 'USERS_FAIL';

export const USERS_INFO_START = 'USERS_INFO_START';
export const USERS_INFO_CONCAT = 'USERS_INFO_CONCAT';
export const USERS_INFO_SUCCESS = 'USERS_INFO_SUCCESS';
export const USERS_INFO_FAIL = 'USERS_INFO_FAIL';

export const USER_ROLES = 'USER_ROLES';

export const USER_PROFILE = 'USER_PROFILE';
export const USER_PROFILE_CLEAR = 'USER_PROFILE_CLEAR';

export const USER_START = 'USER_START';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_FAIL = 'USER_FAIL';

export const AUTH_USER_START = 'AUTH_USER_START';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_USER_FAIL = 'AUTH_USER_FAIL';

export const CORPORATES_START = 'CORPORATES_START';
export const CORPORATES_SUCCESS = 'CORPORATES_SUCCESS';
export const CORPORATES_FAIL = 'CORPORATES_FAIL';

export const CORPORATE_START = 'CORPORATE_START';
export const CORPORATE_SUCCESS = 'CORPORATE_SUCCESS';
export const CORPORATE_FAIL = 'CORPORATE_FAIL';

export const ITEM_LABORATORIES = 'ITEM_LABORATORIES';
export const ITEM_CATEGORIES = 'ITEM_CATEGORIES';
export const LABORATORY_PROCEDURES = 'LABORATORY_PROCEDURES';
export const LABORATORY_SERVICES = 'LABORATORY_SERVICES';

export const ITEMS_START = 'ITEMS_START';
export const ITEMS_CONCAT = 'ITEMS_CONCAT';
export const ITEMS_SUCCESS = 'ITEMS_SUCCESS';
export const ITEMS_FAIL = 'ITEMS_FAIL';

export const ITEM_START = 'ITEM_START';
export const ITEM_SUCCESS = 'ITEM_SUCCESS';
export const ITEM_FAIL = 'ITEM_FAIL';

export const PACKAGES_TYPES = 'PACKAGES_TYPES';

export const PACKAGES_START = 'PACKAGES_START';
export const PACKAGES_CONCAT = 'PACKAGES_CONCAT';
export const PACKAGES_SUCCESS = 'PACKAGES_SUCCESS';
export const PACKAGES_FAIL = 'PACKAGES_FAIL';

export const PACKAGE_START = 'PACKAGE_START';
export const PACKAGE_SUCCESS = 'PACKAGE_SUCCESS';
export const PACKAGE_FAIL = 'PACKAGE_FAIL';

export const COUNTRIES = 'COUNTRIES';
export const NATIONALITIES = 'NATIONALITIES';

export const PAYMENT_BANKS = 'PAYMENT_BANKS';

export const BRANCHES_START = 'BRANCHES_START';
export const BRANCHES_SUCCESS = 'BRANCHES_SUCCESS';
export const BRANCHES_FAIL = 'BRANCHES_FAIL';

export const BRANCH_START = 'BRANCH_START';
export const BRANCH_SUCCESS = 'BRANCH_SUCCESS';
export const BRANCH_FAIL = 'BRANCH_FAIL';

export const PATIENTS_START = 'PATIENTS_START';
export const PATIENTS_CONCAT = 'PATIENTS_CONCAT';
export const PATIENTS_SUCCESS = 'PATIENTS_SUCCESS';
export const PATIENTS_FAIL = 'PATIENTS_FAIL';

export const PATIENTS_DATE_START = 'PATIENTS_DATE_START';
export const PATIENTS_DATE_CONCAT = 'PATIENTS_DATE_CONCAT';
export const PATIENTS_DATE_SUCCESS = 'PATIENTS_DATE_SUCCESS';
export const PATIENTS_DATE_FAIL = 'PATIENTS_DATE_FAIL';

export const PATIENT_START = 'PATIENT_START';
export const PATIENT_SUCCESS = 'PATIENT_SUCCESS';
export const PATIENT_FAIL = 'PATIENT_FAIL';

export const DOCTORS_START = 'DOCTORS_START';
export const DOCTORS_SUCCESS = 'DOCTORS_SUCCESS';
export const DOCTORS_FAIL = 'DOCTORS_FAIL';

export const DOCTOR_START = 'DOCTOR_START';
export const DOCTOR_SUCCESS = 'DOCTOR_SUCCESS';
export const DOCTOR_FAIL = 'DOCTOR_FAIL';

export const REFERRALS_START = 'REFERRALS_START';
export const REFERRALS_SUCCESS = 'REFERRALS_SUCCESS';
export const REFERRALS_FAIL = 'REFERRALS_FAIL';

export const REFERRAL_START = 'REFERRAL_START';
export const REFERRAL_SUCCESS = 'REFERRAL_SUCCESS';
export const REFERRAL_FAIL = 'REFERRAL_FAIL';

export const TRANSLIST_CLEAR = 'TRANSLIST_CLEAR';
export const TRANSLIST_START = 'TRANSLIST_START';
export const TRANSLIST_CONCAT = 'TRANSLIST_CONCAT';
export const TRANSLIST_SUCCESS = 'TRANSLIST_SUCCESS';
export const TRANSLIST_FAIL = 'TRANSLIST_FAIL';

export const ONHOLD_TRANS_CLEAR = 'ONHOLD_TRANS_CLEAR';
export const ONHOLD_TRANS_START = 'ONHOLD_TRANS_START';
export const ONHOLD_TRANS_CONCAT = 'ONHOLD_TRANS_CONCAT';
export const ONHOLD_TRANS_SUCCESS = 'ONHOLD_TRANS_SUCCESS';
export const ONHOLD_TRANS_FAIL = 'ONHOLD_TRANS_FAIL';

export const TRANSACTION_START = 'TRANSACTION_START';
export const TRANSACTION_SUCCESS = 'TRANSACTION_SUCCESS';
export const TRANSACTION_FAIL = 'TRANSACTION_FAIL';
export const TRANSACTION_CLEAR_DATA = 'TRANSACTION_CLEAR_DATA';

export const MENU_LIST = 'MENU_LIST';
export const USER_MENUS = 'USER_MENUS';
export const USER_ROLES_START = 'USER_ROLES_START';
export const USER_ROLES_SUCCESS = 'USER_ROLES_SUCCESS';
export const USER_ROLES_FAIL = 'USER_ROLES_FAIL';

export const USER_ROLE_START = 'USER_ROLE_START';
export const USER_ROLE_SUCCESS = 'USER_ROLE_SUCCESS';
export const USER_ROLE_FAIL = 'USER_ROLE_FAIL';

export const LAB_XR_CLEAR_LIST = 'LAB_XR_CLEAR_LIST';
export const LAB_XR_START = 'LAB_XR_START';
export const LAB_XR_CONCAT = 'LAB_XR_CONCAT';
export const LAB_XR_SUCCESS = 'LAB_XR_SUCCESS';
export const LAB_XR_FAIL = 'LAB_XR_FAIL';

export const LAB_PE_CLEAR_LIST = 'LAB_PE_CLEAR_LIST';
export const LAB_PE_START = 'LAB_PE_START';
export const LAB_PE_CONCAT = 'LAB_PE_CONCAT';
export const LAB_PE_SUCCESS = 'LAB_PE_SUCCESS';
export const LAB_PE_FAIL = 'LAB_PE_FAIL';

export const LAB_US_CLEAR_LIST = 'LAB_US_CLEAR_LIST';
export const LAB_US_START = 'LAB_US_START';
export const LAB_US_CONCAT = 'LAB_US_CONCAT';
export const LAB_US_SUCCESS = 'LAB_US_SUCCESS';
export const LAB_US_FAIL = 'LAB_US_FAIL';

export const LAB_E2D_CLEAR_LIST = 'LAB_E2D_CLEAR_LIST';
export const LAB_E2D_START = 'LAB_E2D_START';
export const LAB_E2D_CONCAT = 'LAB_E2D_CONCAT';
export const LAB_E2D_SUCCESS = 'LAB_E2D_SUCCESS';
export const LAB_E2D_FAIL = 'LAB_E2D_FAIL';

export const LAB_ECG_CLEAR_LIST = 'LAB_ECG_CLEAR_LIST';
export const LAB_ECG_START = 'LAB_ECG_START';
export const LAB_ECG_CONCAT = 'LAB_ECG_CONCAT';
export const LAB_ECG_SUCCESS = 'LAB_ECG_SUCCESS';
export const LAB_ECG_FAIL = 'LAB_ECG_FAIL';

export const LAB_CM_CLEAR_LIST = 'LAB_CM_CLEAR_LIST';
export const LAB_CM_START = 'LAB_CM_START';
export const LAB_CM_CONCAT = 'LAB_CM_CONCAT';
export const LAB_CM_SUCCESS = 'LAB_CM_SUCCESS';
export const LAB_CM_FAIL = 'LAB_CM_FAIL';

export const LAB_MB_CLEAR_LIST = 'LAB_MB_CLEAR_LIST';
export const LAB_MB_START = 'LAB_MB_START';
export const LAB_MB_CONCAT = 'LAB_MB_CONCAT';
export const LAB_MB_SUCCESS = 'LAB_MB_SUCCESS';
export const LAB_MB_FAIL = 'LAB_MB_FAIL';

export const LAB_BT_CLEAR_LIST = 'LAB_BT_CLEAR_LIST';
export const LAB_BT_START = 'LAB_BT_START';
export const LAB_BT_CONCAT = 'LAB_BT_CONCAT';
export const LAB_BT_SUCCESS = 'LAB_BT_SUCCESS';
export const LAB_BT_FAIL = 'LAB_BT_FAIL';

export const LAB_HE_CLEAR_LIST = 'LAB_HE_CLEAR_LIST';
export const LAB_HE_START = 'LAB_HE_START';
export const LAB_HE_CONCAT = 'LAB_HE_CONCAT';
export const LAB_HE_SUCCESS = 'LAB_HE_SUCCESS';
export const LAB_HE_FAIL = 'LAB_HE_FAIL';

export const LAB_CH_CLEAR_LIST = 'LAB_CH_CLEAR_LIST';
export const LAB_CH_START = 'LAB_CH_START';
export const LAB_CH_CONCAT = 'LAB_CH_CONCAT';
export const LAB_CH_SUCCESS = 'LAB_CH_SUCCESS';
export const LAB_CH_FAIL = 'LAB_CH_FAIL';

export const LAB_SE_CLEAR_LIST = 'LAB_SE_CLEAR_LIST';
export const LAB_SE_START = 'LAB_SE_START';
export const LAB_SE_CONCAT = 'LAB_SE_CONCAT';
export const LAB_SE_SUCCESS = 'LAB_SE_SUCCESS';
export const LAB_SE_FAIL = 'LAB_SE_FAIL';

export const LAB_TO_CLEAR_LIST = 'LAB_TO_CLEAR_LIST';
export const LAB_TO_START = 'LAB_TO_START';
export const LAB_TO_CONCAT = 'LAB_TO_CONCAT';
export const LAB_TO_SUCCESS = 'LAB_TO_SUCCESS';
export const LAB_TO_FAIL = 'LAB_TO_FAIL';

export const LAB_IND_CLEAR_LIST = 'LAB_IND_CLEAR_LIST';
export const LAB_IND_START = 'LAB_IND_START';
export const LAB_IND_CONCAT = 'LAB_IND_CONCAT';
export const LAB_IND_SUCCESS = 'LAB_IND_SUCCESS';
export const LAB_IND_FAIL = 'LAB_IND_FAIL';

export const LAB_NRS_CLEAR_LIST = 'LAB_NRS_CLEAR_LIST';
export const LAB_NRS_START = 'LAB_NRS_START';
export const LAB_NRS_CONCAT = 'LAB_NRS_CONCAT';
export const LAB_NRS_SUCCESS = 'LAB_NRS_SUCCESS';
export const LAB_NRS_FAIL = 'LAB_NRS_FAIL';

export const LAB_PENDING_CLEAR = 'LAB_PENDING_CLEAR';
export const LAB_PENDING_START = 'LAB_PENDING_START';
export const LAB_PENDING_SUCCESS = 'LAB_PENDING_SUCCESS';
export const LAB_PENDING_FAIL = 'LAB_PENDING_FAIL';

export const LAB_PENDING_CLEAR_Over3Days = 'LAB_PENDING_CLEAR_Over3Days';
export const LAB_PENDING_START_Over3Days = 'LAB_PENDING_START_Over3Days';
export const LAB_PENDING_SUCCESS_Over3Days = 'LAB_PENDING_SUCCESS_Over3Days';
export const LAB_PENDING_FAIL_Over3Days = 'LAB_PENDING_FAIL_Over3Days';

export const LAB_PENDING_CLEAR_Less3Days = 'LAB_PENDING_CLEAR_Less3Days';
export const LAB_PENDING_START_Less3Days = 'LAB_PENDING_START_Less3Days';
export const LAB_PENDING_SUCCESS_Less3Days = 'LAB_PENDING_SUCCESS_Less3Days';
export const LAB_PENDING_FAIL_Less3Days = 'LAB_PENDING_FAIL_Less3Days';

export const LAB_TXN_CLEAR_LIST = 'LAB_TXN_CLEAR_LIST';
export const LAB_TXN_START = 'LAB_TXN_START';
export const LAB_TXN_CONCAT = 'LAB_TXN_CONCAT';
export const LAB_TXN_SUCCESS = 'LAB_TXN_SUCCESS';
export const LAB_TXN_FAIL = 'LAB_TXN_FAIL';

export const CASHIER_EOD_START = 'CASHIER_EOD_START';
export const CASHIER_EOD_SUCCESS = 'CASHIER_EOD_SUCCESS';
export const CASHIER_EOD_FAIL = 'CASHIER_EOD_FAIL';
export const CASHIER_EOD_CLEAR_DATA = 'CASHIER_EOD_CLEAR_DATA';

export const AUDITOR_EOD_START = 'AUDITOR_EOD_START';
export const AUDITOR_EOD_SUCCESS = 'AUDITOR_EOD_SUCCESS';
export const AUDITOR_EOD_FAIL = 'AUDITOR_EOD_FAIL';
export const AUDITOR_EOD_CLEAR_DATA = 'AUDITOR_EOD_CLEAR_DATA';

export const AUDITOR_EOD_EXCEL_START = 'AUDITOR_EOD_EXCEL_START';
export const AUDITOR_EOD_EXCEL_SUCCESS = 'AUDITOR_EOD_EXCEL_SUCCESS';
export const AUDITOR_EOD_EXCEL_FAIL = 'AUDITOR_EOD_EXCEL_FAIL';

export const AUDITOR_SOA_CLEAR_DATA = 'AUDITOR_SOA_CLEAR_DATA';
export const AUDITOR_SOA_UNBILLED_CLEAR = 'AUDITOR_SOA_UNBILLED_CLEAR';
export const AUDITOR_SOA_UNBILLED_START = 'AUDITOR_SOA_UNBILLED_START';
export const AUDITOR_SOA_UNBILLED_CONCAT = 'AUDITOR_SOA_UNBILLED_CONCAT';
export const AUDITOR_SOA_UNBILLED_SUCCESS = 'AUDITOR_SOA_UNBILLED_SUCCESS';
export const AUDITOR_SOA_UNBILLED_FAIL = 'AUDITOR_SOA_UNBILLED_FAIL';

export const AUDITOR_SOA_START = 'AUDITOR_SOA_START';
export const AUDITOR_SOA_SUCCESS = 'AUDITOR_SOA_SUCCESS';
export const AUDITOR_SOA_FAIL = 'AUDITOR_SOA_FAIL';

export const PAYMENT_SOA_START = 'PAYMENT_SOA_START';
export const PAYMENT_SOA_SUCCESS = 'PAYMENT_SOA_SUCCESS';
export const PAYMENT_SOA_FAIL = 'PAYMENT_SOA_FAIL';

export const CHARGETO_SOA_CLEAR = 'CHARGETO_SOA_CLEAR';
export const CHARGETO_SOA_START = 'CHARGETO_SOA_START';
export const CHARGETO_SOA_CONCAT = 'CHARGETO_SOA_CONCAT';
export const CHARGETO_SOA_SUCCESS = 'CHARGETO_SOA_SUCCESS';
export const CHARGETO_SOA_FAIL = 'CHARGETO_SOA_FAIL';

export const SOA_PAYMENT_CLEAR = 'SOA_PAYMENT_CLEAR';
export const SOA_PAYMENT_START = 'SOA_PAYMENT_START';
export const SOA_PAYMENT_CONCAT = 'SOA_PAYMENT_CONCAT';
export const SOA_PAYMENT_SUCCESS = 'SOA_PAYMENT_SUCCESS';
export const SOA_PAYMENT_FAIL = 'SOA_PAYMENT_FAIL';

export const SOA_SUMMARY_CLEAR = 'SOA_SUMMARY_CLEAR';
export const SOA_SUMMARY_START = 'SOA_SUMMARY_START';
export const SOA_SUMMARY_SUCCESS = 'SOA_SUMMARY_SUCCESS';
export const SOA_SUMMARY_FAIL = 'SOA_SUMMARY_FAIL';

export const SOA_SUMMARY_REPORT_START = 'SOA_SUMMARY_REPORT_START';
export const SOA_SUMMARY_REPORT_SUCCESS = 'SOA_SUMMARY_REPORT_SUCCESS';
export const SOA_SUMMARY_REPORT_FAIL = 'SOA_SUMMARY_REPORT_FAIL';

export const SOA_LOADING_START = 'SOA_LOADING_START';
export const SOA_LOADING_SUCCESS = 'SOA_LOADING_SUCCESS';
export const SOA_LOADING_FAIL = 'SOA_LOADING_FAIL';

export const EMAIL_START = 'EMAIL_START';
export const EMAIL_SUCCESS = 'EMAIL_SUCCESS';
export const EMAIL_FAIL = 'EMAIL_FAIL';

export const CUPMEDAR_START = 'CUPMEDAR_START';
export const CUPMEDAR_SUCCESS = 'CUPMEDAR_SUCCESS';
export const CUPMEDAR_FAIL = 'CUPMEDAR_FAIL';

export const MARKER_START = 'MARKER_START';
export const MARKER_SUCCESS = 'MARKER_SUCCESS';
export const MARKER_FAIL = 'MARKER_FAIL';

export const MARKER_INVENTORY_START = 'MARKER_INVENTORY_START';
export const MARKER_INVENTORY_SUCCESS = 'MARKER_INVENTORY_SUCCESS';
export const MARKER_INVENTORY_FAIL = 'MARKER_INVENTORY_FAIL';

export const EXPORT_START = 'EXPORT_START'
export const EXPORT_SUCCESS = 'EXPORT_SUCCESS'
export const EXPORT_FAIL = 'EXPORT_FAIL'


export const REFERENCE_LABORATORY_START = 'REFERENCE_LABORATORY_START'
export const REFERENCE_LABORATORY_CONCAT = 'REFERENCE_LABORATORY_CONCAT';
export const REFERENCE_LABORATORY_SUCCESS = 'REFERENCE_LABORATORY_SUCCESS'
export const REFERENCE_LABORATORY_FAIL = 'REFERENCE_LABORATORY_FAIL'

export const SOP_START = 'SOP_START'
export const SOP_CLEAR = 'SOP_CLEAR'
export const SOP_SUCCESS = 'SOP_SUCCESS'
export const SOP_FAIL = 'SOP_FAIL'

export const SOP_LIST_START = 'SOP_LIST_START'
export const SOP_LIST_CLEAR = 'SOP_LIST_CLEAR'
export const SOP_LIST_SUCCESS = 'SOP_LIST_SUCCESS'
export const SOP_LIST_FAIL = 'SOP_LIST_FAIL'

export const SOP_PAYMENT_LIST_START = 'SOP_PAYMENT_LIST_START'
export const SOP_PAYMENT_LIST_CONCAT = 'SOP_PAYMENT_LIST_CONCAT'
export const SOP_PAYMENT_LIST_SUCCESS = 'SOP_PAYMENT_LIST_SUCCESS'
export const SOP_PAYMENT_LIST_FAIL = 'SOP_PAYMENT_LIST_FAIL'

export const SOP_LOADING_START = 'SOP_LOADING_START';
export const SOP_LOADING_SUCCESS = 'SOP_LOADING_SUCCESS';
export const SOP_LOADING_FAIL = 'SOP_LOADING_FAIL';

export const SOP_SUMMARY_CLEAR = 'SOP_SUMMARY_CLEAR';
export const SOP_SUMMARY_START = 'SOP_SUMMARY_START';
export const SOP_SUMMARY_SUCCESS = 'SOP_SUMMARY_SUCCESS';
export const SOP_SUMMARY_FAIL = 'SOP_SUMMARY_FAIL';
